---
title: "R Notebook"
output: html_notebook
---


#NFL 2019-2020 EDA 

#Phil Ramontal


#Libraries
```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(pwr)
```

```{r}
#Data Import
nfl_19 <- read.csv("pbp-2019.csv")
nfl_19$GameDate <- as.Date(nfl_19$GameDate)
(nfl_19)
```

```{r}

#Hypothesis: Yards gained on 4th 

#NFL Week 1 2019
nfl <- nfl_19 [nfl_19$GameDate >= "2019/09/05" & nfl_19$GameDate <= "2020/02/03",]


#Plays with less than 4 yards to get 1st down
nfl_togo<- filter(nfl,nfl$Down == "4")

#Subset "run' & "pass"

nfl_run <- subset(nfl_togo, nfl_togo$PlayType == "RUSH")

#Mean of yards gained from run play

mean(nfl_run$Yards)

#2.45 Avg yards gained

#t.test

t.test(nfl_run$Yards, mu = 2.45, alternative = "two.sided", conf.level = 0.95)

nfl_pass <- subset(nfl_togo, nfl_togo$PlayType == "PASS")

#Mean of yards gained from pass play

mean(nfl_pass$Yards)

#5.98 yards gained

#t.test

t_test <- t.test(nfl_pass$Yards, mu = 6, alternative = "two.sided", conf.level = 0.95)
t_test

cohen.ES(test = "t", size = "medium")

#Pass power.t.test
power_4 <- pwr.t.test(d = .2, sig.level = 0.05 , power = .8, type = "one.sample")

plot(power_4)
```
 
 

```{r}
#Hypothesis: Yards gained on 3rd down

nfl1 <- nfl_19 [nfl_19$GameDate >= "2019/09/05" & nfl_19$GameDate <= "2020/02/03",]

#Plays on down 3
nfl_togo_3<- filter(nfl,nfl$Down == "3")

#Subset "run' & "pass"

nfl_run_3 <- subset(nfl_togo_3, nfl_togo_3$PlayType == "RUSH")

#Mean of yards gained from run play

mean(nfl_run_3$Yards)

#3.71 Avg yards gained

#t.test

t.test(nfl_run_3$Yards, mu = 4, alternative = "two.sided", conf.level = 0.95)

nfl_pass_3_1 <- subset(nfl_togo_3, nfl_togo_3$PlayType == "PASS")

#Mean of yards gained from pass play

mean(nfl_pass_3_1$Yards)

#7.25 yards gained

#t.test

t_test_3 <- t.test(nfl_pass_3_1$Yards, mu = 7, alternative = "two.sided", conf.level = 0.95)
t_test_3

cohen.ES(test = "t", size = "medium")

#power.t.test
power_3 <- pwr.t.test( d = .2, sig.level = 0.05 , power = .8, type = "one.sample" )

plot(power_3)
```


```{r}
#Hypothesis: Yards gained on 2nd down

#Plays on down 2
nfl_togo_2<- filter(nfl,nfl$Down == "2")

#Subset "run' & "pass"

nfl_run_2 <- subset(nfl_togo_2, nfl_togo_2$PlayType == "RUSH")

#Mean of yards gained from run play

mean(nfl_run_2$Yards)

#4.53 Avg yards gained

#t.test

t.test_2 <- t.test(nfl_run_3$Yards, mu = 5 , alternative = "two.sided", conf.level = 0.95)
t.test_2

nfl_pass_2 <- subset(nfl_togo_2, nfl_togo_2$PlayType == "PASS")

#Mean of yards gained from pass play

mean(nfl_pass_2$Yards)

#7.25 yards gained

#t.test

t_test_2nd <- t.test(nfl_pass_2$Yards, mu = 7, alternative = "two.sided", conf.level = 0.95)
t_test_2nd

cohen.ES(test = "t", size = "large")

#power.t.test
power_2 <- pwr.t.test( d = .5, sig.level = 0.05 , power = .8, type = "one.sample")

plot(power_2)
```

# Second Down Analysis

```{r}
#2nd >5 and <5  subset
#20 yard interval  
#add in formation type 


#down 2 
down_2 <- nfl[nfl$Down == "2" & nfl$ToGo <= 5 ,]

nfl_2_run <- subset(down_2, down_2$PlayType == "RUSH")

run_mean <- mean(nfl_2_run$Yards)

t_2nd_run <- t.test(nfl_2_run$Yards, mu = 4,  alternative = "two.sided", conf.level = 0.95)

nfl_2_pass <- subset(down_2, down_2$PlayType == "PASS")

pass_mean <- mean(nfl_2_pass$Yards)

t_2nd_pass <- t.test(nfl_2_run$Yards, mu = 6,  alternative = "two.sided", conf.level = 0.95)

power_2nd <- pwr.t.test( d = .2, sig.level = 0.05 , power = .99, type = "one.sample")

plot(power_2nd)

#Yard 0-20
yard_20 <- subset(down_2, down_2$YardLine <= "20")

ggplot(yard_20, aes(x = Formation, y = Yards)) + geom_bar(stat = "identity", position = "dodge")

nfl_20_run <- subset(yard_20, yard_20$PlayType == "RUSH")

#anova yard 20 
yard20_run.aov <- aov(Yards ~ Formation, data = nfl_20_run )
summary(yard20_run.aov)

run_mean_20 <- mean(nfl_20_run$Yards)

t_20_run <- t.test(nfl_20_run$Yards, mu = 5,  alternative = "two.sided", conf.level = 0.95)
t_20_run

nfl_20_pass <- subset(yard_20, yard_20$PlayType == "PASS")

pass_20_mean <- mean(nfl_20_pass$Yards)

t_20_pass <- t.test(nfl_20_pass$Yards, mu = 7,  alternative = "two.sided", conf.level = 0.95)
t_20_pass

power_20 <- pwr.t.test( d = .2, sig.level = 0.05 , power = .80, type = "one.sample")


#sample size 198 need for .8 power, 458 sample size for .99 power

#yard between 20 and 40
yard_40 <- subset(down_2, down_2$YardLine <= "40")

ggplot(yard_40, aes(x = yard_40$Yards)) + geom_histogram(aes(stat = "identity", position = "dodge", fill = Formation))

nfl_40_run <- subset(yard_40, yard_40$PlayType == "RUSH")

run_mean_40 <- mean(nfl_40_run$Yards)
run_mean_40
#5.15

t_40_run <- t.test(nfl_40_run$Yards, mu = 5,  alternative = "two.sided", conf.level = 0.95)
t_40_run
#p-value 0.69

nfl_40_pass <- subset(yard_40, yard_40$PlayType == "PASS")

pass_40_mean <- mean(nfl_40_pass$Yards)
pass_40_mean
#8.10

t_40_pass <- t.test(nfl_40_pass$Yards, mu = 8,  alternative = "two.sided", conf.level = 0.95)
t_40_pass
#p-value 0.83

power_40 <- pwr.t.test( d = .5, sig.level = 0.05 , power = .80, type = "one.sample")
plot(power_40)

#yards between 40 and 60 
yard_60 <- subset(down_2, down_2$YardLine <= "60")

ggplot(yard_60, aes(x = yard_60$Yards)) + geom_bar(aes(stat = "identity", position = "dodge", fill = Formation))

nfl_60_run <- subset(yard_60, yard_60$PlayType == "RUSH")

run_mean_60 <- mean(nfl_60_run$Yards)
run_mean_60
#5.08

t_60_run <- t.test(nfl_60_run$Yards, mu = 5,  alternative = "two.sided", conf.level = 0.95)
t_60_run
#p-value 0.75

nfl_60_pass <- subset(yard_60, yard_60$PlayType == "PASS")

pass_60_mean <- mean(nfl_60_pass$Yards)
pass_60_mean
#7.54

t_60_pass <- t.test(nfl_60_pass$Yards, mu = 7.5,  alternative = "two.sided", conf.level = 0.95)
t_60_pass
#p-value 0.90

power_60 <- pwr.t.test( d = .8, sig.level = 0.05 , power = .8, type = "one.sample")
plot(power_40)

#yards between 60 and 80
yard_80 <- subset(down_2, down_2$YardLine <= "80")

ggplot(yard_80, aes(x = yard_80$Yards)) + geom_histogram(aes(stat = "identity", position = "dodge", fill = Formation ))

nfl_80_run <- subset(yard_80, yard_80$PlayType == "RUSH")

run_mean_80 <- mean(nfl_80_run$Yards)
run_mean_80
#4.78

t_80_run <- t.test(nfl_80_run$Yards, mu = 4.8,  alternative = "two.sided", conf.level = 0.95)
t_80_run
#p-value 0.95

nfl_80_pass <- subset(yard_80, yard_80$PlayType == "PASS")

pass_80_mean <- mean(nfl_80_pass$Yards)
pass_80_mean
#7.38

t_80_pass <- t.test(nfl_80_pass$Yards, mu = 7,  alternative = "two.sided", conf.level = 0.95)
t_80_pass
#p-value 0.21

power_80 <- pwr.t.test( d = .8, sig.level = 0.05 , power = .80, type = "one.sample")
plot(power_80)

```



```{r}
#DOWN 2 MEAN YARDS ON VARIOUS FORMATIONS 


#Run inside yard 20
#Limited data

for_run_shot <- subset(yard_20, yard_20$Formation == "NO HUDDLE" & yard_20$PlayType == "RUSH")
 
mean(for_run_shot$Yards)
#7.25

run_aov_shot <- aov(Yards  ~  YardLine + ToGo, data = for_run_shot)
summary.aov(run_aov_shot)

for_run_cen <- subset(yard_20, yard_20$Formation == "UNDER CENTER" & yard_20$PlayType == "RUSH" )

mean(for_run_cen$Yards)
#3.7

run_aov_cen <- aov(Yards~  YardLine + ToGo, data = for_run_cen)
summary.aov(run_aov_cen)
plot(run_aov_cen)


for_run_nh <- subset(yard_20, yard_20$Formation == "NO HUDDLE SHOTGUN" & yard_20$PlayType == "RUSH" )

mean(for_run_nh$Yards)
#5.6

run_aov_nh <- aov(Yards ~  YardLine + ToGo, data = for_run_nh)
summary.aov(run_aov_nh)
plot(run_aov_nh)

for_run_gun <- subset(yard_20, yard_20$Formation == "SHOTGUN" & yard_20$PlayType == "RUSH")

mean(for_run_gun$Yards)

run_aov_gun<- aov(Yards~  YardLine + ToGo, data = for_run_gun)
summary.aov(run_aov_gun)
plot(run_aov_gun)
#6.25

#Tukey test run play yard 20 interval

TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_run_shot))
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_run_cen))
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_run_nh))
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_run_gun))

#Pass inside yard 20
#DATA ONLY HAS 1 OBSERVATION 
for_pass_shot <- subset(yard_20, yard_20$Formation == "NO HUDDLE" & yard_20$PlayType == "PASS")

mean(for_pass_shot$Yards)
#0


for_pass_cen <- subset(yard_20, yard_20$Formation == "UNDER CENTER" & yard_20$PlayType == "PASS" )

mean(for_pass_cen$Yards)
#5.33

pass_aov_cen <- aov(Yards~  YardLine + ToGo, data = for_pass_cen)
summary.aov(pass_aov_cen)
plot(pass_aov_cen)

for_pass_nh <- subset(yard_20, yard_20$Formation == "NO HUDDLE SHOTGUN" & yard_20$PlayType == "PASS" )

mean(for_pass_nh$Yards)
#8.46

pass_aov_nh <- aov(Yards~  YardLine + ToGo, data = for_pass_nh)
summary.aov(pass_aov_nh)
plot(pass_aov_nh)

for_pass_gun <- subset(yard_20, yard_20$Formation == "SHOTGUN" & yard_20$PlayType == "PASS")

mean(for_pass_gun$Yards)
#7.19

pass_aov_gun <- aov(Yards~  YardLine + ToGo, data = for_pass_gun)
summary.aov(pass_aov_gun)
plot(pass_aov_gun)

#Tukey test

#TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_pass_shot)) Not enough observations
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_pass_cen))
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_pass_nh))
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_pass_gun))
```


#Yard 40
```{r}
for_run_shot40 <- subset(yard_40, yard_40$Formation == "NO HUDDLE" & yard_40$PlayType == "RUSH")

mean(for_run_shot40$Yards)
#5.7

run_aov_shot40 <- aov(Yards~  YardLine + ToGo, data = for_run_shot40)
summary.aov(run_aov_shot40)
plot(run_aov_shot40)

  
for_run_cen40 <- subset(yard_40, yard_40$Formation == "UNDER CENTER" & yard_40$PlayType == "RUSH" )

mean(for_run_cen40$Yards)
#5.03

run_aov_cen40 <- aov(Yards~  YardLine + ToGo, data = for_run_cen40)
summary.aov(run_aov_cen40)
plot(run_aov_cen40)

for_run_nh40 <- subset(yard_40, yard_40$Formation == "NO HUDDLE SHOTGUN" & yard_40$PlayType == "RUSH" )

mean(for_run_nh40$Yards)
#4

run_aov_nh40 <- aov(Yards~  YardLine + ToGo, data = for_run_nh40)
summary.aov(run_aov_nh40)
plot(run_aov_nh40)

for_run_gun40 <- subset(yard_40, yard_40$Formation == "SHOTGUN" & yard_40$PlayType == "RUSH")

mean(for_run_gun40$Yards)
#5.7

run_aov_gun40 <- aov(Yards~  YardLine + ToGo, data = for_run_gun40)
summary.aov(run_aov_gun40)
plot(run_aov_gun40)

#Tukey Test

TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_run_shot40))
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_run_cen40))
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_run_nh40))
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_run_gun40))


#pass yard 40 

for_pass_shot40 <- subset(yard_40, yard_40$Formation == "NO HUDDLE" & yard_40$PlayType == "PASS")

mean(for_pass_shot40$Yards)
#4.7

pass_aov_shot40 <- aov(Yards~  YardLine + ToGo, data = for_pass_shot40)
summary.aov(pass_aov_shot40)
plot(pass_aov_shot40)

  
for_pass_cen40 <- subset(yard_40, yard_40$Formation == "UNDER CENTER" & yard_40$PlayType == "PASS" )

mean(for_pass_cen40$Yards)
#9.83

pass_aov_cen40 <- aov(Yards~  YardLine + ToGo, data = for_pass_cen40)
summary.aov(pass_aov_cen40)
plot(pass_aov_cen40)

for_pass_nh40 <- subset(yard_40, yard_40$Formation == "NO HUDDLE SHOTGUN" & yard_40$PlayType == "PASS" )

mean(for_pass_nh40$Yards)
#8.49 

pass_aov_nh40 <- aov(Yards~  YardLine + ToGo, data = for_pass_nh40)
summary.aov(pass_aov_nh40)
plot(pass_aov_nh40)

for_pass_gun40 <- subset(yard_40, yard_40$Formation == "SHOTGUN" & yard_40$PlayType == "PASS")

mean(for_pass_gun40$Yards)
#7.3

pass_aov_gun40 <- aov(Yards~  YardLine + ToGo, data = for_pass_gun40)
summary.aov(pass_aov_gun40)
plot(pass_aov_gun40)  

#Tukey test

TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_pass_shot40))
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_pass_cen40))
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_pass_nh40))
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_pass_gun40))
```


#Yard 60
```{r}
#yard 60 run

for_run_shot60 <- subset(yard_60, yard_40$Formation == "NO HUDDLE" & yard_60$PlayType == "RUSH")

mean(for_run_shot60$Yards)
#5.6

run_aov_shot60 <- aov(Yards~  YardLine + ToGo, data = for_run_shot60)
summary.aov(run_aov_shot60)
plot(run_aov_shot60)

  
for_run_cen60 <- subset(yard_60, yard_60$Formation == "UNDER CENTER" & yard_60$PlayType == "RUSH" )

mean(for_run_cen60$Yards)
#4.88

run_aov_cen60 <- aov(Yards~  YardLine + ToGo, data = for_run_cen60)
summary.aov(run_aov_cen60)
plot(run_aov_cen60)

for_run_nh60 <- subset(yard_60, yard_60$Formation == "NO HUDDLE SHOTGUN" & yard_60$PlayType == "RUSH" )

mean(for_run_nh60$Yards)
#5.5

run_aov_nh60 <- aov(Yards~  YardLine + ToGo, data = for_run_nh60)
summary.aov(run_aov_nh60)
plot(run_aov_nh60)

for_run_gun60 <- subset(yard_60, yard_60$Formation == "SHOTGUN" & yard_60$PlayType == "RUSH")

mean(for_run_gun60$Yards)
#5.5

run_aov_gun60 <- aov(Yards~  YardLine + ToGo, data = for_run_gun60)
summary.aov(run_aov_gun60)
plot(run_aov_gun60)  

#Tukey test

TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_run_shot60))
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_run_cen60))
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_run_nh60))
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_run_gun60))

#pass yard 60

for_pass_shot60 <- subset(yard_60, yard_60$Formation == "NO HUDDLE" & yard_60$PlayType == "PASS")

mean(for_pass_shot60$Yards)
#5.7

pass_aov_shot60 <- aov(Yards~  YardLine + ToGo, data = for_pass_shot60)
summary.aov(pass_aov_shot60)
plot(pass_aov_shot60)

  
for_pass_cen60 <- subset(yard_60, yard_60$Formation == "UNDER CENTER" & yard_60$PlayType == "PASS" )

mean(for_pass_cen60$Yards)
#9.37

pass_aov_cen60 <- aov(Yards~  YardLine + ToGo, data = for_pass_cen60)
summary.aov(pass_aov_cen60)
plot(pass_aov_cen60)

for_pass_nh60 <- subset(yard_60, yard_60$Formation == "NO HUDDLE SHOTGUN" & yard_60$PlayType == "PASS" )

mean(for_pass_nh60$Yards)
#7.91 

pass_aov_nh60 <- aov(Yards~  YardLine + ToGo, data = for_pass_nh60)
summary.aov(pass_aov_nh60)
plot(pass_aov_nh60)

for_pass_gun60 <- subset(yard_60, yard_60$Formation == "SHOTGUN" & yard_60$PlayType == "PASS")

mean(for_pass_gun60$Yards)
#6.65

pass_aov_gun60 <- aov(Yards~  YardLine + ToGo, data = for_pass_gun60)
summary.aov(pass_aov_gun60)
plot(pass_aov_gun60)  

#Tukey test

TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_pass_shot60))
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_pass_cen60))
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_pass_nh60))
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_pass_gun60))
```


#Yard 80 

```{r}

#yard 80 run 

for_run_shot80 <- subset(yard_80, yard_80$Formation == "NO HUDDLE" & yard_80$PlayType == "RUSH")

mean(for_run_shot80$Yards)
#4.04

run_aov_shot80 <- aov(Yards~  YardLine + ToGo, data = for_run_shot80)
summary.aov(run_aov_shot80)
plot(run_aov_shot80)

  
for_run_cen80 <- subset(yard_80, yard_80$Formation == "UNDER CENTER" & yard_80$PlayType == "RUSH" )

mean(for_run_cen80$Yards)
#4.57

run_aov_cen80 <- aov(Yards~  YardLine + ToGo, data = for_run_cen80)
summary.aov(run_aov_cen80)
plot(run_aov_cen80)

for_run_nh80 <- subset(yard_80, yard_80$Formation == "NO HUDDLE SHOTGUN" & yard_80$PlayType == "RUSH" )

mean(for_run_nh80$Yards)
#5.17

run_aov_nh80 <- aov(Yards~  YardLine + ToGo, data = for_run_nh80)
summary.aov(run_aov_nh80)
plot(run_aov_nh80)

for_run_gun80 <- subset(yard_80, yard_80$Formation == "SHOTGUN" & yard_80$PlayType == "RUSH")

mean(for_run_gun80$Yards)
#5.23

run_aov_gun80 <- aov(Yards~  YardLine + ToGo, data = for_run_gun80)
summary.aov(run_aov_gun80)
plot(run_aov_gun80)  

#Tukey test

TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_run_shot80))
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_run_cen80))
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_run_nh80))
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_run_gun80))

#yard 80 pass 

for_pass_shot80 <- subset(yard_80, yard_80$Formation == "NO HUDDLE" & yard_80$PlayType == "PASS")

mean(for_pass_shot80$Yards)
#4.95

pass_aov_shot80 <- aov(Yards~  YardLine + ToGo, data = for_pass_shot80)
summary.aov(pass_aov_shot80)
plot(pass_aov_shot80)

  
for_pass_cen80 <- subset(yard_80, yard_80$Formation == "UNDER CENTER" & yard_80$PlayType == "PASS" )

mean(for_pass_cen80$Yards)
#9.22

pass_aov_cen80 <- aov(Yards~  YardLine + ToGo, data = for_pass_cen80)
summary.aov(pass_aov_cen80)
plot(pass_aov_cen80)

for_pass_nh80 <- subset(yard_80, yard_80$Formation == "NO HUDDLE SHOTGUN" & yard_80$PlayType == "PASS" )

mean(for_pass_nh80$Yards)
#7.50

pass_aov_nh80 <- aov(Yards~  YardLine + ToGo, data = for_pass_nh80)
summary.aov(pass_aov_nh80)
plot(pass_aov_nh80)

for_pass_gun80 <- subset(yard_80, yard_80$Formation == "SHOTGUN" & yard_80$PlayType == "PASS")

mean(for_pass_gun80$Yards)
#6.64

pass_aov_gun80 <- aov(Yards~  YardLine + ToGo, data = for_pass_gun80)
summary.aov(pass_aov_gun80)  
plot(pass_aov_gun80)  


#Tukey test

TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_pass_shot80))
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_pass_cen80))
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_pass_nh80))
TukeyHSD(aov(Yards~as.factor(ToGo) + as.factor(YardLine), for_pass_gun80))
```

